package com.camera.custom.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.camera.custom.Foto;

import com.camera.custom.dao.FotoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fotoDaoConfig;

    private final FotoDao fotoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fotoDaoConfig = daoConfigMap.get(FotoDao.class).clone();
        fotoDaoConfig.initIdentityScope(type);

        fotoDao = new FotoDao(fotoDaoConfig, this);

        registerDao(Foto.class, fotoDao);
    }
    
    public void clear() {
        fotoDaoConfig.clearIdentityScope();
    }

    public FotoDao getFotoDao() {
        return fotoDao;
    }

}
